package com.liyz.dubbo.common.desensitize;

/**
 * 注释:
 *
 * @author liyangzhen
 * @version 1.0.0
 * @date 2022/4/21 13:50
 */
public class aaa {
    
    private String a = "{\n" +
            "  \"beforeHandInfo\": \"\",\n" +
            "  \"actualPaymentAccept\": \"0.00\",\n" +
            "  \"actualPaymentCash\": \"1000.00\",\n" +
            "  \"repayDelay\": 0,\n" +
            "  \"usableRefundDeductionAmount\": \"1000.00\",\n" +
            "  \"refundDeductionAmount\": \"0.00\",\n" +
            "  \"usableRebateDeductionAmount\": \"16.00\",\n" +
            "  \"rebateDeductionAmount\": \"0.00\",\n" +
            "  \"usableDeductionAmount\": \"0.00\",\n" +
            "  \"deductionAmount\": \"0.00\",\n" +
            "  \"paymentAmount\": \"1000.00\",\n" +
            "  \"paymentCash\": \"1000.00\",\n" +
            "  \"companyRebateAmount\": \"0.00\",\n" +
            "  \"paymentAccept\": \"0.00\",\n" +
            "  \"gmtPaid\": \"2022-01-01\",\n" +
            "  \"factoryValueDate\": \"\",\n" +
            "  \"marginAmount\": \"0.00\",\n" +
            "  \"exposureAmount\": \"0.00\",\n" +
            "  \"factPayInterestAmount\": \"0.00\",\n" +
            "  \"endorseAmount\": \"0.00\",\n" +
            "  \"billBankId\": \"\",\n" +
            "  \"payBankAccount\": \"\",\n" +
            "  \"orderCode\": \"20220415000035\",\n" +
            "  \"thirdBankPayInfo\": [],\n" +
            "  \"bankPayInfo\": [{\n" +
            "    \"bankId\": 1002,\n" +
            "    \"bankDetail\": {\n" +
            "      \"v\": [1000, 1001, 1002],\n" +
            "      \"options\": [{\n" +
            "        \"label\": \"中信银行\",\n" +
            "        \"value\": 1000,\n" +
            "        \"children\": [{\n" +
            "          \"label\": \"中信银行杭州滨江支行\",\n" +
            "          \"value\": 1001,\n" +
            "          \"children\": [{\n" +
            "            \"label\": \"7332410182600053579\",\n" +
            "            \"value\": 1002\n" +
            "          }, {\n" +
            "            \"label\": \"8110801012501303996\",\n" +
            "            \"value\": 1052\n" +
            "          }]\n" +
            "        }, {\n" +
            "          \"label\": \"中信银行绍兴嵊州支行\",\n" +
            "          \"value\": 1003,\n" +
            "          \"children\": []\n" +
            "        }, {\n" +
            "          \"label\": \"中信银行杭州之江支行\",\n" +
            "          \"value\": 1005,\n" +
            "          \"children\": []\n" +
            "        }, {\n" +
            "          \"label\": \"中信银行杭州萧山支行\",\n" +
            "          \"value\": 1007,\n" +
            "          \"children\": []\n" +
            "        }]\n" +
            "      }, {\n" +
            "        \"label\": \"工商银行\",\n" +
            "        \"value\": 1009,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"华夏银行\",\n" +
            "        \"value\": 1012,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"兴业银行\",\n" +
            "        \"value\": 1017,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"招商银行\",\n" +
            "        \"value\": 1020,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"联合银行\",\n" +
            "        \"value\": 1023,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"中国银行\",\n" +
            "        \"value\": 1028,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"杭州银行\",\n" +
            "        \"value\": 1033,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"浙商银行股份有限公司\",\n" +
            "        \"value\": 1036,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"上海银行\",\n" +
            "        \"value\": 1041,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"中国农业银行杭州\",\n" +
            "        \"value\": 1044,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"宁波银行\",\n" +
            "        \"value\": 1049,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"渤海银行\",\n" +
            "        \"value\": 1053,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"农业银行\",\n" +
            "        \"value\": 1056,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"江苏银行\",\n" +
            "        \"value\": 1059,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"中信滨江\",\n" +
            "        \"value\": 1062,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"建设银行\",\n" +
            "        \"value\": 1068,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"平安银行\",\n" +
            "        \"value\": 1081,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"ddddd\",\n" +
            "        \"value\": 1114,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"湖州银行\",\n" +
            "        \"value\": 1120,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"温州银行\",\n" +
            "        \"value\": 1123,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"测试银行\",\n" +
            "        \"value\": 1131,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"固克保证金\",\n" +
            "        \"value\": 1139,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"铃鹿（厂家）保证金\",\n" +
            "        \"value\": 1142,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"铃鹿保证金\",\n" +
            "        \"value\": 1145,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"亚士保证金\",\n" +
            "        \"value\": 1148,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"东莞保证金\",\n" +
            "        \"value\": 1151,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"吉林保证金\",\n" +
            "        \"value\": 1154,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"预付\",\n" +
            "        \"value\": 1158,\n" +
            "        \"children\": []\n" +
            "      }, {\n" +
            "        \"label\": \"苏宁银行\",\n" +
            "        \"value\": 1161,\n" +
            "        \"children\": []\n" +
            "      }],\n" +
            "      \"thirdName\": \"7332410182600053579\"\n" +
            "    },\n" +
            "    \"bankAccount\": \"7332410182600053579\",\n" +
            "    \"depositAmount\": 1000,\n" +
            "    \"companyId\": \"202204140100010001OSCK0000000003\",\n" +
            "    \"bankName\": \"中信银行杭州滨江支行\",\n" +
            "    \"depositRemain\": \"\"\n" +
            "  }],\n" +
            "  \"factPayInterest\": [],\n" +
            "  \"directBankList\": [],\n" +
            "  \"normalBankList\": [{\n" +
            "    \"bankId\": \"\",\n" +
            "    \"bankDetail\": {\n" +
            "      \"v\": [],\n" +
            "      \"options\": []\n" +
            "    },\n" +
            "    \"bankAccount\": \"\",\n" +
            "    \"depositAmount\": \"\",\n" +
            "    \"companyId\": \"202204140100010001OSCK0000000003\"\n" +
            "  }],\n" +
            "  \"taskId\": \"4366425411956738\",\n" +
            "  \"memberId\": \"luwenjun\",\n" +
            "  \"flowFiles\": [{\n" +
            "    \"category\": \"1\",\n" +
            "    \"files\": []\n" +
            "  }, {\n" +
            "    \"category\": \"2\",\n" +
            "    \"files\": []\n" +
            "  }, {\n" +
            "    \"category\": \"3\",\n" +
            "    \"files\": []\n" +
            "  }, {\n" +
            "    \"category\": \"4\",\n" +
            "    \"files\": []\n" +
            "  }, {\n" +
            "    \"category\": \"5\",\n" +
            "    \"files\": []\n" +
            "  }, {\n" +
            "    \"category\": \"6\",\n" +
            "    \"files\": []\n" +
            "  }],\n" +
            "  \"isBankDirect\": false,\n" +
            "  \"isPass\": \"Y\",\n" +
            "  \"rebateAmount\": 10\n" +
            "}";
}
