# server
server:
  port: 7075
# spring
spring:
  application:
    name: dubbo-service-job
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/job?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#dubbo
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    id: dubbo
    port: 20775
  provider:
    filter: remoteServiceExceptionFilter,-exception
    version: 1.0.0
  consumer:
    version: 1.0.0
    check: false
    cluster: failfast
    timeout: 2000
  registry:
    timeout: 5000
    address: nacos://localhost:8848
  metadata-report:
    address: nacos://localhost:8848
# job
elasticjob:
  reg-center:
    server-lists: localhost:2181
    namespace: dubbo-service-job


