server:
  port: 7077

spring:
  application:
    name: dubbo-service-job
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/job?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    useLocalTransactionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false

#dubbo
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    id: dubbo
    port: 20777
  provider:
    filter: remoteServiceExceptionFilter,-exception
    version: 1.0.0
  consumer:
    version: 1.0.0
    check: false
    cluster: failfast
    timeout: 2000
  registry:
    timeout: 5000
    file: service-job-cache.properties
    address: nacos://localhost:8848
  metadata-report:
    address: nacos://localhost:8848

logging:
  level:
    com.liyz.dubbo.service.job.dao: debug
    org.springframework.transaction.*: debug
    org.springframework.jdbc.*: debug

elasticjob:
  auto:
    enabled: true
  enabled: false
  tracing:
    type: RDB
  reg-center:
    server-lists: localhost:2181
    namespace: dubbo-service-job

